//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorPetrov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersImport
    {
        public int id { get; set; }
        public int idTypeParner { get; set; }
        public int idPartner { get; set; }
        public string Director { get; set; }
        public string email { get; set; }
        public string phoneNum { get; set; }
        public int idindex { get; set; }
        public int idDistrict { get; set; }
        public int idCity { get; set; }
        public int idStreet { get; set; }
        public int Home { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
    
        public virtual City City { get; set; }
        public virtual District District { get; set; }
        public virtual Index Index { get; set; }
        public virtual PartnerName PartnerName { get; set; }
        public virtual Street Street { get; set; }
        public virtual Type Type { get; set; }
    }
}
