//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorPetrov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProductsImport
    {
        public int id { get; set; }
        public string ProductName { get; set; }
        public int idPartner { get; set; }
        public int CountProduct { get; set; }
        public System.DateTime DateSale { get; set; }
    
        public virtual PartnerName PartnerName { get; set; }
    }
}
