//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorPetrov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypeImport
    {
        public int id { get; set; }
        public string TypeProductName { get; set; }
        public Nullable<int> idProductType { get; set; }
        public decimal CofTypeProd { get; set; }
    
        public virtual ProductImports ProductImports { get; set; }
        public virtual Type Type { get; set; }
    }
}
